[package]
name = "parcl-v3-api-client"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.21.2"
reqwest = { version = "0.11.13", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-sdk = ">=1.16, <=2.1.6"
thiserror = "2"
